# Generated by Django 4.2.17 on 2025-01-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loses',
            new_name='losses',
        ),
    ]
