# Generated by Django 4.2.18 on 2025-01-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(check=models.Q(('first_user__lt', models.F('second_user'))), name='first_user_lt_second_user'),
        ),
    ]
