# Generated by Django 4.2.17 on 2025-01-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_loses_user_losses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='playerAmount',
            new_name='player_amount',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('left_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_player_matches', to='api.user')),
                ('right_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_player_matches', to='api.user')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='api.user')),
            ],
        ),
    ]
