# Generated by Django 4.2.18 on 2025-01-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_result'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='first_user_lt_second_user',
        ),
    ]
