# Generated by Django 4.2.18 on 2025-01-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_chat_first_user_lt_second_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
